---
sidebar: sidebar
api: true
explorer: false
permalink: 'delete-security-anti-ransomware-suspects-.html'
summary: 'Clear suspect files of a volume'
---

= Clear suspect files of a volume

[.api-doc-operation .api-doc-operation-delete]#DELETE# [.api-doc-code-block]#`/security/anti-ransomware/suspects/{volume.uuid}`#

*Introduced In:* 9.10

Clears either all the suspect files of a volume or suspect files of a volume based on file format or suspect time provided.

== Related ONTAP commands

* `security anti-ransomware volume attack clear-suspect`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|volume.uuid
|string
|path
|True
a|Identification of the Anti-ransomware suspect file for the deletion.

* format: uuid


|is_false_positive
|boolean
|query
|False
a|Specifies whether the suspected ransomware activity is a false positive or not.

* Default value:


|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "string"
  }
}
====

== Response

```
Status: 202, Accepted
```

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


//end collapsible .Definitions block
====
