---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-storage-cluster.html'
summary: 'Report cluster-wide storage details across different tiers'
---

= Report cluster-wide storage details across different tiers

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/storage/cluster`#

*Introduced In:* 9.6

Retrieves cluster-wide storage details across the different tiers. By default, this endpoint returns all fields.
Storage details include storage efficiency, block storage and cloud storage information.
Supports the following roles: admin, and readonly.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|block_storage.size
|integer
|query
|False
a|Filter by block_storage.size

* Introduced in: 9.14


|block_storage.available
|integer
|query
|False
a|Filter by block_storage.available

* Introduced in: 9.14


|block_storage.medias.type
|string
|query
|False
a|Filter by block_storage.medias.type

* Introduced in: 9.14


|block_storage.medias.used
|integer
|query
|False
a|Filter by block_storage.medias.used

* Introduced in: 9.14


|block_storage.medias.efficiency_without_snapshots.logical_used
|integer
|query
|False
a|Filter by block_storage.medias.efficiency_without_snapshots.logical_used

* Introduced in: 9.14


|block_storage.medias.efficiency_without_snapshots.ratio
|number
|query
|False
a|Filter by block_storage.medias.efficiency_without_snapshots.ratio

* Introduced in: 9.14


|block_storage.medias.efficiency_without_snapshots.savings
|integer
|query
|False
a|Filter by block_storage.medias.efficiency_without_snapshots.savings

* Introduced in: 9.14


|block_storage.medias.efficiency_without_snapshots_flexclones.logical_used
|integer
|query
|False
a|Filter by block_storage.medias.efficiency_without_snapshots_flexclones.logical_used

* Introduced in: 9.14


|block_storage.medias.efficiency_without_snapshots_flexclones.ratio
|number
|query
|False
a|Filter by block_storage.medias.efficiency_without_snapshots_flexclones.ratio

* Introduced in: 9.14


|block_storage.medias.efficiency_without_snapshots_flexclones.savings
|integer
|query
|False
a|Filter by block_storage.medias.efficiency_without_snapshots_flexclones.savings

* Introduced in: 9.14


|block_storage.medias.size
|integer
|query
|False
a|Filter by block_storage.medias.size

* Introduced in: 9.14


|block_storage.medias.available
|integer
|query
|False
a|Filter by block_storage.medias.available

* Introduced in: 9.14


|block_storage.medias.efficiency.logical_used
|integer
|query
|False
a|Filter by block_storage.medias.efficiency.logical_used

* Introduced in: 9.14


|block_storage.medias.efficiency.ratio
|number
|query
|False
a|Filter by block_storage.medias.efficiency.ratio

* Introduced in: 9.14


|block_storage.medias.efficiency.savings
|integer
|query
|False
a|Filter by block_storage.medias.efficiency.savings

* Introduced in: 9.14


|block_storage.medias.physical_used
|integer
|query
|False
a|Filter by block_storage.medias.physical_used

* Introduced in: 9.14


|block_storage.physical_used
|integer
|query
|False
a|Filter by block_storage.physical_used

* Introduced in: 9.14


|block_storage.used
|integer
|query
|False
a|Filter by block_storage.used

* Introduced in: 9.14


|block_storage.inactive_data
|integer
|query
|False
a|Filter by block_storage.inactive_data

* Introduced in: 9.14


|cloud_storage.used
|integer
|query
|False
a|Filter by cloud_storage.used

* Introduced in: 9.14


|efficiency_without_snapshots.logical_used
|integer
|query
|False
a|Filter by efficiency_without_snapshots.logical_used

* Introduced in: 9.14


|efficiency_without_snapshots.ratio
|number
|query
|False
a|Filter by efficiency_without_snapshots.ratio

* Introduced in: 9.14


|efficiency_without_snapshots.savings
|integer
|query
|False
a|Filter by efficiency_without_snapshots.savings

* Introduced in: 9.14


|efficiency_without_snapshots_flexclones.logical_used
|integer
|query
|False
a|Filter by efficiency_without_snapshots_flexclones.logical_used

* Introduced in: 9.14


|efficiency_without_snapshots_flexclones.ratio
|number
|query
|False
a|Filter by efficiency_without_snapshots_flexclones.ratio

* Introduced in: 9.14


|efficiency_without_snapshots_flexclones.savings
|integer
|query
|False
a|Filter by efficiency_without_snapshots_flexclones.savings

* Introduced in: 9.14


|efficiency.logical_used
|integer
|query
|False
a|Filter by efficiency.logical_used

* Introduced in: 9.14


|efficiency.ratio
|number
|query
|False
a|Filter by efficiency.ratio

* Introduced in: 9.14


|efficiency.savings
|integer
|query
|False
a|Filter by efficiency.savings

* Introduced in: 9.14


|fields
|array[string]
|query
|False
a|Specify the fields to return.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|block_storage
|link:#block_storage[block_storage]
a|Configuration information for the locally attached portion of the storage across the cluster. When a cloud store is also used by the storage, this is referred to as the performance tier.


|cloud_storage
|link:#cloud_storage[cloud_storage]
a|Configuration information for the cloud storage portion of all the aggregates across the cluster. This is referred to as the capacity tier.


|efficiency
|link:#efficiency[efficiency]
a|Storage efficiency.

=== Platform Specifics

* *Unified ONTAP*: Available for GET requests.
* readOnly: 1
* Introduced in: 9.6


|efficiency_without_snapshots
|link:#efficiency_without_snapshots[efficiency_without_snapshots]
a|Storage efficiency that does not include the savings provided by snapshots.


|efficiency_without_snapshots_flexclones
|link:#efficiency_without_snapshots_flexclones[efficiency_without_snapshots_flexclones]
a|Storage efficiency that does not include the savings provided by snapshots and FlexClone volumes.

=== Platform Specifics

* *Unified ONTAP*: Available for GET requests.
* readOnly: 1
* Introduced in: 9.9


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "block_storage": {
    "available": 0,
    "inactive_data": 0,
    "medias": [
      {
        "efficiency": {
          "logical_used": 0,
          "ratio": 0,
          "savings": 0
        },
        "efficiency_without_snapshots": {
          "logical_used": 0,
          "ratio": 0,
          "savings": 0
        },
        "efficiency_without_snapshots_flexclones": {
          "logical_used": 0,
          "ratio": 0,
          "savings": 0
        },
        "type": "string"
      }
    ],
    "physical_used": 0,
    "size": 0,
    "used": 0
  },
  "efficiency": {
    "logical_used": 0,
    "ratio": 0,
    "savings": 0
  },
  "efficiency_without_snapshots": {
    "logical_used": 0,
    "ratio": 0,
    "savings": 0
  },
  "efficiency_without_snapshots_flexclones": {
    "logical_used": 0,
    "ratio": 0,
    "savings": 0
  }
}
====

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 9240637
| This operation is not supported on this platform.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.



[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#efficiency]
[.api-collapsible-fifth-title]
efficiency

Storage efficiency.

=== Platform Specifics

* *Unified ONTAP*: Available for GET requests.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|logical_used
|integer
a|Logical used


|ratio
|number
a|Data reduction ratio (logical_used / used)


|savings
|integer
a|Space saved by storage efficiencies (logical_used - used)


|===


[#efficiency_without_snapshots]
[.api-collapsible-fifth-title]
efficiency_without_snapshots

Storage efficiency that does not include the savings provided by snapshots.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|logical_used
|integer
a|Logical used


|ratio
|number
a|Data reduction ratio (logical_used / used)


|savings
|integer
a|Space saved by storage efficiencies (logical_used - used)


|===


[#efficiency_without_snapshots_flexclones]
[.api-collapsible-fifth-title]
efficiency_without_snapshots_flexclones

Storage efficiency that does not include the savings provided by snapshots and FlexClone volumes.

=== Platform Specifics

* *Unified ONTAP*: Available for GET requests.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|logical_used
|integer
a|Logical used


|ratio
|number
a|Data reduction ratio (logical_used / used)


|savings
|integer
a|Space saved by storage efficiencies (logical_used - used)


|===


[#medias]
[.api-collapsible-fifth-title]
medias

[cols=3*,options=header]
|===
|Name
|Type
|Description

|available
|integer
a|Available space across the cluster based on media type.


|efficiency
|link:#efficiency[efficiency]
a|Storage efficiency.

=== Platform Specifics

* *Unified ONTAP*: Available for GET requests.
* Introduced in: 9.7


|efficiency_without_snapshots
|link:#efficiency_without_snapshots[efficiency_without_snapshots]
a|Storage efficiency that does not include the savings provided by snapshots.


|efficiency_without_snapshots_flexclones
|link:#efficiency_without_snapshots_flexclones[efficiency_without_snapshots_flexclones]
a|Storage efficiency that does not include the savings provided by snapshots and FlexClone volumes.

=== Platform Specifics

* *Unified ONTAP*: Available for GET requests.
* Introduced in: 9.9


|physical_used
|integer
a|Total physical used space across the cluster based on media type.


|size
|integer
a|Total space across the cluster based on media type.


|type
|string
a|The type of media being used.


|used
|integer
a|Used space across the cluster based on media type.

=== Platform Specifics

* *Unified ONTAP*: Available for GET requests.
* format: int64
* Introduced in: 9.6
* x-nullable: true


|===


[#block_storage]
[.api-collapsible-fifth-title]
block_storage

Configuration information for the locally attached portion of the storage across the cluster. When a cloud store is also used by the storage, this is referred to as the performance tier.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|available
|integer
a|Available space across the cluster.


|inactive_data
|integer
a|Inactive data across the cluster.

=== Platform Specifics

* *Unified ONTAP*: Available for GET requests.
* format: int64
* readOnly: 1
* Introduced in: 9.7
* x-nullable: true


|medias
|array[link:#medias[medias]]
a|Configuration information based on type of media. For example, SSD media type information includes the sum of all the SSD storage across the cluster.


|physical_used
|integer
a|Total physical used space across the cluster.


|size
|integer
a|Total space across the cluster.


|used
|integer
a|Used space (includes volume reserves) across the cluster.

=== Platform Specifics

* *Unified ONTAP*: Available for GET requests.
* format: int64
* readOnly: 1
* Introduced in: 9.6
* x-nullable: true


|===


[#cloud_storage]
[.api-collapsible-fifth-title]
cloud_storage

Configuration information for the cloud storage portion of all the aggregates across the cluster. This is referred to as the capacity tier.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|used
|integer
a|Total space used in cloud.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
