settings:
  name: ONTAP REST API reference 
  lipi_enabled: false
  github_edit: false
  internal:
    pdf_enabled: true
    avatars_enabled: false
    api_enabled: true
  prod:
    pdf_enabled: true
    avatars_enabled: false
    harmony_enabled: false
    api_enabled: true
  versions: 
  # This Repo
  - version-number: "9.16.1"
    url: /ontap-restapi-9161
  # Additional Releases
  - version-number: "9.15.1"
    url: /ontap-restapi-9151
  - version-number: "9.14.1"
    url: /ontap-restapi-9141
  - version-number: "9.13.1"
    url: /ontap-restapi-9131
  - version-number: "9.12.1"
    url: /ontap-restapi-9121
  - version-number: "9.11.1"
    url: /ontap-restapi-9111
  - version-number: "9.10.1"
    url: /ontap-restapi-9101  
  - version-number: "9.9.1"
    url: /ontap-restapi-991
  - version-number: "9.8"
    url: /ontap-restapi-98 
  - version-number: "9.7"
    url: /ontap-restapi-97 
  - version-number: "9.6"  
    url: /ontap-restapi-96   

sidebar: 
  entries:
    - title: ONTAP 9.16.1 REST API reference 
      url: /index.html
    - section: ontap
    - title: Legal notices
      url: /legal-notices.html

product-family: 
  name: ONTAP
  repo: ontap-family


